Update manual-update-cli-docs.yaml

diff --git a/.github/workflows/manual-update-cli-docs.yaml b/.github/workflows/manual-update-cli-docs.yaml
--- a/.github/workflows/manual-update-cli-docs.yaml
+++ b/.github/workflows/manual-update-cli-docs.yaml
@@ -32,7 +32,7 @@ jobs:
         fi
         # let's check if the version is already published
         curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/open-component-model/ocm/releases > versions.txt
-        grep -Fxq '${{ github.event.inputs.version }}' versions.txt && echo "Version found" || echo "Version not found" && exit 1
+        grep -Fxq '${{ github.event.inputs.version }}' versions.txt && echo "Version (${{ github.event.inputs.version }}) found" || echo "Version (${{ github.event.inputs.version }}) not found!" && exit 1
         echo "RELEASE_VERSION=$(echo ${{ github.event.inputs.version }} )" >> $GITHUB_ENV
     - name: Publish Event
       uses: peter-evans/repository-dispatch@v3
