Update manual-update-cli-docs.yaml

diff --git a/.github/workflows/manual-update-cli-docs.yaml b/.github/workflows/manual-update-cli-docs.yaml
--- a/.github/workflows/manual-update-cli-docs.yaml
+++ b/.github/workflows/manual-update-cli-docs.yaml
@@ -14,21 +14,26 @@ jobs:
     name: Create new "Release Publish Event"
     runs-on: ubuntu-latest
     permissions:
-      id-token: 'write'
+      contents: write
+      id-token: write
+      packages: write
     steps:
-    - name: Ensure proper version
-      run: |
-        if ![ -n "${{ github.event.inputs.version }}" ]; then
-          echo "Version not provided"
-          exit 1
-        fi
-        echo "RELEASE_VERSION=$(echo ${{ github.event.inputs.version }} | tr -d ['v'])" >> $GITHUB_ENV
     - name: Generate token
       id: generate_token
       uses: tibdex/github-app-token@v2
       with:
         app_id: ${{ secrets.OCMBOT_APP_ID }}
         private_key: ${{ secrets.OCMBOT_PRIV_KEY }}
+    - name: Ensure proper version
+      run: |
+        if ![ -n "${{ github.event.inputs.version }}" ]; then
+          echo "Version not provided"
+          exit 1
+        fi
+        # let's check if the version is already published
+        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/open-component-model/ocm/releases > versions.txt
+        grep -Fxq '${{ github.event.inputs.version }}' versions.txt && echo "Version found" || echo "Version not found" && exit 1
+        echo "RELEASE_VERSION=$(echo ${{ github.event.inputs.version }} )" >> $GITHUB_ENV
     - name: Publish Event
       uses: peter-evans/repository-dispatch@v3
       with:
